---
hero_image: images/banner.png
listed: true
copyedit: false
title: Archery
description: Shoot arrows as close to the bullseye as you can.
version: 4
last_tested: 2025-01-02
steps:
- title: What you will make
- title: Aiming arrows
- title: Shooting arrows
  completion:
  - engaged
  - internal
- title: Challenge
  challenge: true
- title: What can you do now?
