---
hero_image: images/banner.png
listed: true
copyedit: false
title: アーチェリー
description: できるだけまとの中心に矢をあてよう！
version: 4
last_tested: 2019-04-18
steps:
- title: はじめに
  completion: engaged
- title: ねらいをつける
  completion: internal
- title: 矢をはなつ
- title: 'チャレンジ: ちがうスコア'
  challenge: true
- title: 次は何をしましょうか？
