---
hero_image: images/banner.png
listed: true
copyedit: false
title: アーチェリー
description: できるだけまとの中心に矢をあてよう！
version: 4
last_tested: 2019-04-18
steps:
- title: はじめに
- title: ねらいをつける
- title: 矢をはなつ
  completion:
  - engaged
  - internal
- title: 'チャレンジ: ちがうスコア'
  challenge: true