---
hero_image: images/banner.png
listed: true
copyedit: false
title: Tiro com arco
description: Dispara flechas o mais ao centro do alvo que conseguires.
version: 4
last_tested: 2019-04-18
steps:
- title: Introdução
- title: Apontando flechas
- title: Atirar flechas
  completion:
  - engaged
  - internal
- title: 'Desafio: pontuações diferentes'
  challenge: true