---
hero_image: images/banner.png
listed: true
copyedit: false
title: Tiro con arco
description: Dispara flechas tan cerca del blanco de la diana como puedas.
version: 4
last_tested: 2019-04-18
steps:
- title: Introducción
- title: Apuntando las flechas
- title: Disparando flechas
  completion:
  - engaged
  - internal
- title: 'Desafío: Diferentes puntuaciones'
  challenge: true