---
hero_image: images/banner.png
listed: true
copyedit: false
title: Bogenschießen
description: Schieße Pfeile so nah wie möglich an das Bullseye.
version: 4
last_tested: 2019-04-18
steps:
- title: Einleitung
  completion: engaged
- title: Pfeile zielen
  completion: internal
- title: Pfeile schießen
- title: 'Herausforderung: Unterschiedliche Punkte'
  challenge: true
- title: Wie geht es weiter?
