---
hero_image: images/banner.png
listed: true
copyedit: false
title: Bogenschießen
description: Schieße Pfeile so nah wie möglich an das Bullseye.
version: 4
last_tested: 2019-04-18
steps:
  - 
    title: Einleitung
  - 
    title: Pfeile zielen
  - 
    title: Pfeile schießen
    completion:
      - engaged
      - internal
  - 
    title: 'Herausforderung: Unterschiedliche Punkte'
    challenge: true
  - 
    title: Wie geht es weiter?
