---
hero_image: images/banner.png
listed: true
copyedit: false
title: Tiro ao alvo
description: Atire flechas o mais próximo possível do centro do alvo.
version: 4
last_tested: 2019-04-18
steps:
- title: Introdução
  completion: engaged
- title: Mirando as flechas
  completion: internal
- title: Atirando as flechas
- title: 'Desafio: pontuações diferentes'
  challenge: true
- title: E agora?
