---
hero_image: images/banner.png
listed: true
copyedit: false
title: Łucznik
description: Strzel z łuku jak najbliżej środka tarczy.
version: 4
last_tested: 2019-04-18
steps:
- title: Wprowadzenie
  completion: engaged
- title: Celowanie strzałami
  completion: internal
- title: Strzelanie z łuku
- title: 'Wyzwanie: Różne wyniki'
  challenge: true
- title: Co dalej?
