---
hero_image: images/banner.png
listed: true
copyedit: false
title: Łucznik
description: Naucz się, jak stworzyć grę, w której gracz musi trafić strzałą jak najbliżej środka tarczy.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Łucznik
  - 
    title: Aiming arrows
  - 
    title: Shooting arrows
  - 
    title: 'Challenge: Different scores'
    challenge: true
  - 
    title: 'What next?'
