---
hero_image: images/banner.png
listed: true
copyedit: false
title: Τοξοβολία
description: Ρίξτε τα βέλη όσο πιο κοντά στο bullseye μπορείτε.
version: 4
last_tested: 2019-04-18
steps:
  - 
    title: Εισαγωγή
  - 
    title: Βέλη στόχευσης
  - 
    title: Βέλη σκοποβολής
  - 
    title: 'Πρόκληση: Διαφορετικές βαθμολογίες'
    challenge: true
  - 
    title: 'Τι υπάρχει στη συνέχεια;'
