---
hero_image: images/banner.png
listed: true
copyedit: false
title: Tir à l'arc
description: Tire des flèches aussi près que possible du centre de la cible.
version: 4
last_tested: 2019-04-18
steps:
- title: Introduction
- title: Viser avec les flèches
- title: Tirer des flèches
  completion:
  - engaged
  - internal
- title: 'Défi: scores différents'
  challenge: true
- title: Et ensuite ?
