---
hero_image: images/banner.png
listed: true
copyedit: false
title: Tiro con l'arco
description: Tira le frecce il più vicino possibile al centro del bersaglio.
version: 4
last_tested: 2019-04-18
steps:
  - title: Introduzione
  - title: Mirare
  - title: Scoccare le frecce
  - title: 'Sfida: Punteggi differenti'
    challenge: true
  - title: 'E adesso?'
