---
hero_image: images/banner.png
listed: true
copyedit: false
title: Okçuluk
description: Okları hedef tahtasına mümkün olduğunca yakın at.
version: 4
last_tested: 2019-04-18
steps:
  - 
    title: Giriş
  - 
    title: Okla nişan alma
  - 
    title: Okları fırlatma
  - 
    title: 'Meydan Okuma: Farklı skorlar'
    challenge: true
  - 
    title: 'Sırada ne var?'
